services:

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - network_bdd
  
  interface_db:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - network_bdd
      - network_backend

  traitement_backend:
    build:
      context: ./processor
      dockerfile: Dockerfile.dev
    environment:
      FLASK_DEBUG: "1"
      FLASK_ENV: development
      INTERFACE_DB_HOST: interface_db
      INTERFACE_DB_PORT: "5000"
    volumes:
      - ./processor:/app
    depends_on:
      - interface_db
    networks:
      - network_backend
      - network_frontend

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - traitement_backend
    networks:
      - network_frontend


networks:
  network_bdd:
    driver: bridge

  network_backend:
    driver: bridge
  
  network_frontend:
    driver: bridge