global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["spotshare_prometheus:9090"]

  - job_name: node_exporter
    static_configs:
      - targets: ["spotshare_node_exporter:9100"]

  - job_name: cadvisor
    dns_sd_configs:
      - names: ["tasks.spotshare_cadvisor"]
        type: A
        port: 8080

